[phases.setup]
nixPkgs = ['python311', 'nodejs-18_x']

[phases.install]
cmds = [
  'python -m ensurepip --upgrade',
  'python -m pip install -r review-imdb/requirements.txt',
  'cd review-imdb && npm install'
]

[phases.build]
cmds = [
  'cd review-imdb && npm run build'
]

[start]
cmd = 'cd review-imdb && gunicorn api_server:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120'
